/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUtilizadoresRouteImport } from './routes/admin/utilizadores'
import { Route as AdminSubscricoesRouteImport } from './routes/admin/subscricoes'
import { Route as AdminSegurancaRouteImport } from './routes/admin/seguranca'
import { Route as AdminFuncionalidadesRouteImport } from './routes/admin/funcionalidades'
import { Route as AdminAuditoriaRouteImport } from './routes/admin/auditoria'
import { Route as AuthenticatedSeguimentosRouteImport } from './routes/_authenticated/seguimentos'
import { Route as AuthenticatedPessoasRouteImport } from './routes/_authenticated/pessoas'
import { Route as AuthenticatedOportunidadesRouteImport } from './routes/_authenticated/oportunidades'
import { Route as AuthenticatedNegocioRouteImport } from './routes/_authenticated/negocio'
import { Route as AuthenticatedMaisRouteImport } from './routes/_authenticated/mais'
import { Route as AuthenticatedImoveisRouteImport } from './routes/_authenticated/imoveis'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDefinicoesRouteImport } from './routes/_authenticated/definicoes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAssessorRouteImport } from './routes/_authenticated/assessor'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUtilizadoresRoute = AdminUtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubscricoesRoute = AdminSubscricoesRouteImport.update({
  id: '/subscricoes',
  path: '/subscricoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFuncionalidadesRoute = AdminFuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSeguimentosRoute =
  AuthenticatedSeguimentosRouteImport.update({
    id: '/seguimentos',
    path: '/seguimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPessoasRoute = AuthenticatedPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOportunidadesRoute =
  AuthenticatedOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioRoute = AuthenticatedNegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaisRoute = AuthenticatedMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImoveisRoute = AuthenticatedImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDefinicoesRoute = AuthenticatedDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessorRoute = AuthenticatedAssessorRouteImport.update({
  id: '/assessor',
  path: '/assessor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assessor': typeof AuthenticatedAssessorRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/definicoes': typeof AuthenticatedDefinicoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/imoveis': typeof AuthenticatedImoveisRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/negocio': typeof AuthenticatedNegocioRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/pessoas': typeof AuthenticatedPessoasRoute
  '/seguimentos': typeof AuthenticatedSeguimentosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/funcionalidades': typeof AdminFuncionalidadesRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/subscricoes': typeof AdminSubscricoesRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assessor': typeof AuthenticatedAssessorRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/definicoes': typeof AuthenticatedDefinicoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/imoveis': typeof AuthenticatedImoveisRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/negocio': typeof AuthenticatedNegocioRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/pessoas': typeof AuthenticatedPessoasRoute
  '/seguimentos': typeof AuthenticatedSeguimentosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/funcionalidades': typeof AdminFuncionalidadesRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/subscricoes': typeof AdminSubscricoesRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/admin': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/assessor': typeof AuthenticatedAssessorRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/definicoes': typeof AuthenticatedDefinicoesRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/imoveis': typeof AuthenticatedImoveisRoute
  '/_authenticated/mais': typeof AuthenticatedMaisRoute
  '/_authenticated/negocio': typeof AuthenticatedNegocioRoute
  '/_authenticated/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/_authenticated/pessoas': typeof AuthenticatedPessoasRoute
  '/_authenticated/seguimentos': typeof AuthenticatedSeguimentosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/funcionalidades': typeof AdminFuncionalidadesRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/subscricoes': typeof AdminSubscricoesRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assessor'
    | '/calendario'
    | '/definicoes'
    | '/documentos'
    | '/hoje'
    | '/imoveis'
    | '/mais'
    | '/negocio'
    | '/oportunidades'
    | '/pessoas'
    | '/seguimentos'
    | '/admin/auditoria'
    | '/admin/funcionalidades'
    | '/admin/seguranca'
    | '/admin/subscricoes'
    | '/admin/utilizadores'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assessor'
    | '/calendario'
    | '/definicoes'
    | '/documentos'
    | '/hoje'
    | '/imoveis'
    | '/mais'
    | '/negocio'
    | '/oportunidades'
    | '/pessoas'
    | '/seguimentos'
    | '/admin/auditoria'
    | '/admin/funcionalidades'
    | '/admin/seguranca'
    | '/admin/subscricoes'
    | '/admin/utilizadores'
    | '/admin'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/assessor'
    | '/_authenticated/calendario'
    | '/_authenticated/definicoes'
    | '/_authenticated/documentos'
    | '/_authenticated/hoje'
    | '/_authenticated/imoveis'
    | '/_authenticated/mais'
    | '/_authenticated/negocio'
    | '/_authenticated/oportunidades'
    | '/_authenticated/pessoas'
    | '/_authenticated/seguimentos'
    | '/admin/auditoria'
    | '/admin/funcionalidades'
    | '/admin/seguranca'
    | '/admin/subscricoes'
    | '/admin/utilizadores'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/utilizadores': {
      id: '/admin/utilizadores'
      path: '/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AdminUtilizadoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subscricoes': {
      id: '/admin/subscricoes'
      path: '/subscricoes'
      fullPath: '/admin/subscricoes'
      preLoaderRoute: typeof AdminSubscricoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seguranca': {
      id: '/admin/seguranca'
      path: '/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/funcionalidades': {
      id: '/admin/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/admin/funcionalidades'
      preLoaderRoute: typeof AdminFuncionalidadesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/seguimentos': {
      id: '/_authenticated/seguimentos'
      path: '/seguimentos'
      fullPath: '/seguimentos'
      preLoaderRoute: typeof AuthenticatedSeguimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pessoas': {
      id: '/_authenticated/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AuthenticatedPessoasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oportunidades': {
      id: '/_authenticated/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AuthenticatedOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio': {
      id: '/_authenticated/negocio'
      path: '/negocio'
      fullPath: '/negocio'
      preLoaderRoute: typeof AuthenticatedNegocioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mais': {
      id: '/_authenticated/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AuthenticatedMaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imoveis': {
      id: '/_authenticated/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AuthenticatedImoveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/definicoes': {
      id: '/_authenticated/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof AuthenticatedDefinicoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessor': {
      id: '/_authenticated/assessor'
      path: '/assessor'
      fullPath: '/assessor'
      preLoaderRoute: typeof AuthenticatedAssessorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessorRoute: typeof AuthenticatedAssessorRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedDefinicoesRoute: typeof AuthenticatedDefinicoesRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedImoveisRoute: typeof AuthenticatedImoveisRoute
  AuthenticatedMaisRoute: typeof AuthenticatedMaisRoute
  AuthenticatedNegocioRoute: typeof AuthenticatedNegocioRoute
  AuthenticatedOportunidadesRoute: typeof AuthenticatedOportunidadesRoute
  AuthenticatedPessoasRoute: typeof AuthenticatedPessoasRoute
  AuthenticatedSeguimentosRoute: typeof AuthenticatedSeguimentosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessorRoute: AuthenticatedAssessorRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedDefinicoesRoute: AuthenticatedDefinicoesRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedImoveisRoute: AuthenticatedImoveisRoute,
  AuthenticatedMaisRoute: AuthenticatedMaisRoute,
  AuthenticatedNegocioRoute: AuthenticatedNegocioRoute,
  AuthenticatedOportunidadesRoute: AuthenticatedOportunidadesRoute,
  AuthenticatedPessoasRoute: AuthenticatedPessoasRoute,
  AuthenticatedSeguimentosRoute: AuthenticatedSeguimentosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminFuncionalidadesRoute: typeof AdminFuncionalidadesRoute
  AdminSegurancaRoute: typeof AdminSegurancaRoute
  AdminSubscricoesRoute: typeof AdminSubscricoesRoute
  AdminUtilizadoresRoute: typeof AdminUtilizadoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminFuncionalidadesRoute: AdminFuncionalidadesRoute,
  AdminSegurancaRoute: AdminSegurancaRoute,
  AdminSubscricoesRoute: AdminSubscricoesRoute,
  AdminUtilizadoresRoute: AdminUtilizadoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
