/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUtilizadoresRouteImport } from './routes/admin/utilizadores'
import { Route as AdminUtilizacaoRouteImport } from './routes/admin/utilizacao'
import { Route as AdminSuporteRouteImport } from './routes/admin/suporte'
import { Route as AdminSubscricoesRouteImport } from './routes/admin/subscricoes'
import { Route as AdminSegurancaRouteImport } from './routes/admin/seguranca'
import { Route as AdminQualidadeRouteImport } from './routes/admin/qualidade'
import { Route as AdminPlanosRouteImport } from './routes/admin/planos'
import { Route as AdminNegocioRouteImport } from './routes/admin/negocio'
import { Route as AdminIntegracoesFlagsRouteImport } from './routes/admin/integracoes-flags'
import { Route as AdminIntegracoesRouteImport } from './routes/admin/integracoes'
import { Route as AdminGoldensRouteImport } from './routes/admin/goldens'
import { Route as AdminFuncionalidadesRouteImport } from './routes/admin/funcionalidades'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminFaturacaoRouteImport } from './routes/admin/faturacao'
import { Route as AdminDefinicoesRouteImport } from './routes/admin/definicoes'
import { Route as AdminCustosRouteImport } from './routes/admin/custos'
import { Route as AdminConvitesRouteImport } from './routes/admin/convites'
import { Route as AdminComunicacaoRouteImport } from './routes/admin/comunicacao'
import { Route as AdminBetaRouteImport } from './routes/admin/beta'
import { Route as AdminAutonomasRouteImport } from './routes/admin/autonomas'
import { Route as AdminAuditoriaSegurancaRouteImport } from './routes/admin/auditoria-seguranca'
import { Route as AdminAuditoriaRouteImport } from './routes/admin/auditoria'
import { Route as AdminAquisicaoRouteImport } from './routes/admin/aquisicao'
import { Route as AuthenticatedSobreAIaRouteImport } from './routes/_authenticated/sobre-a-ia'
import { Route as AuthenticatedRotinasRouteImport } from './routes/_authenticated/rotinas'
import { Route as AuthenticatedMaisRouteImport } from './routes/_authenticated/mais'
import { Route as AuthenticatedLigarCanalRouteImport } from './routes/_authenticated/ligar-canal'
import { Route as AuthenticatedInteracoesRouteImport } from './routes/_authenticated/interacoes'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedDriveRouteImport } from './routes/_authenticated/drive'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDiversosRouteImport } from './routes/_authenticated/diversos'
import { Route as AuthenticatedDefinicoesRouteImport } from './routes/_authenticated/definicoes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAssessorRouteImport } from './routes/_authenticated/assessor'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedSeguimentosIndexRouteImport } from './routes/_authenticated/seguimentos.index'
import { Route as AuthenticatedPessoasIndexRouteImport } from './routes/_authenticated/pessoas.index'
import { Route as AuthenticatedOportunidadesIndexRouteImport } from './routes/_authenticated/oportunidades.index'
import { Route as AuthenticatedNegociosIndexRouteImport } from './routes/_authenticated/negocios.index'
import { Route as AuthenticatedNegocioIndexRouteImport } from './routes/_authenticated/negocio.index'
import { Route as AuthenticatedImoveisIndexRouteImport } from './routes/_authenticated/imoveis.index'
import { Route as OauthOutlookReturnRouteImport } from './routes/oauth/outlook/return'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth/google-calendar/return'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicBeaconRouteImport } from './routes/api/public/beacon'
import { Route as AdminConsultorIdRouteImport } from './routes/admin/consultor.$id'
import { Route as AuthenticatedSeguimentosIdRouteImport } from './routes/_authenticated/seguimentos.$id'
import { Route as AuthenticatedRotinasIdRouteImport } from './routes/_authenticated/rotinas.$id'
import { Route as AuthenticatedPessoasIdRouteImport } from './routes/_authenticated/pessoas.$id'
import { Route as AuthenticatedOportunidadesIdRouteImport } from './routes/_authenticated/oportunidades.$id'
import { Route as AuthenticatedNegocioFaturacaoRouteImport } from './routes/_authenticated/negocio.faturacao'
import { Route as AuthenticatedNegocioDespesasRouteImport } from './routes/_authenticated/negocio.despesas'
import { Route as AuthenticatedNegocioComissoesRouteImport } from './routes/_authenticated/negocio.comissoes'
import { Route as AuthenticatedInteracoesIdRouteImport } from './routes/_authenticated/interacoes.$id'
import { Route as AuthenticatedImoveisIdRouteImport } from './routes/_authenticated/imoveis.$id'
import { Route as AuthenticatedGruposIdRouteImport } from './routes/_authenticated/grupos.$id'
import { Route as AuthenticatedDriveIdRouteImport } from './routes/_authenticated/drive.$id'
import { Route as AuthenticatedDiversosIdRouteImport } from './routes/_authenticated/diversos.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedOportunidadesProspecaoIndexRouteImport } from './routes/_authenticated/oportunidades.prospecao.index'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksWhatsappTemplateStatusRouteImport } from './routes/api/public/hooks/whatsapp-template-status'
import { Route as ApiPublicHooksTrialLifecycleRouteImport } from './routes/api/public/hooks/trial-lifecycle'
import { Route as ApiPublicHooksTelegramRetentionRouteImport } from './routes/api/public/hooks/telegram-retention'
import { Route as ApiPublicHooksSubmitCheckinTemplateRouteImport } from './routes/api/public/hooks/submit-checkin-template'
import { Route as ApiPublicHooksProactiveTickRouteImport } from './routes/api/public/hooks/proactive-tick'
import { Route as ApiPublicHooksProactivePushRouteImport } from './routes/api/public/hooks/proactive-push'
import { Route as ApiPublicHooksCalendarPollRouteImport } from './routes/api/public/hooks/calendar-poll'
import { Route as ApiPublicHooksBetaExpiryRouteImport } from './routes/api/public/hooks/beta-expiry'
import { Route as AuthenticatedOportunidadesProspecaoIdRouteImport } from './routes/_authenticated/oportunidades.prospecao.$id'
import { Route as AuthenticatedNegocioDespesasIdRouteImport } from './routes/_authenticated/negocio.despesas.$id'
import { Route as AuthenticatedNegocioComissoesIdRouteImport } from './routes/_authenticated/negocio.comissoes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUtilizadoresRoute = AdminUtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUtilizacaoRoute = AdminUtilizacaoRouteImport.update({
  id: '/utilizacao',
  path: '/utilizacao',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubscricoesRoute = AdminSubscricoesRouteImport.update({
  id: '/subscricoes',
  path: '/subscricoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQualidadeRoute = AdminQualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNegocioRoute = AdminNegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntegracoesFlagsRoute = AdminIntegracoesFlagsRouteImport.update({
  id: '/integracoes-flags',
  path: '/integracoes-flags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGoldensRoute = AdminGoldensRouteImport.update({
  id: '/goldens',
  path: '/goldens',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFuncionalidadesRoute = AdminFuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFaturacaoRoute = AdminFaturacaoRouteImport.update({
  id: '/faturacao',
  path: '/faturacao',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDefinicoesRoute = AdminDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustosRoute = AdminCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConvitesRoute = AdminConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComunicacaoRoute = AdminComunicacaoRouteImport.update({
  id: '/comunicacao',
  path: '/comunicacao',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBetaRoute = AdminBetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAutonomasRoute = AdminAutonomasRouteImport.update({
  id: '/autonomas',
  path: '/autonomas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditoriaSegurancaRoute = AdminAuditoriaSegurancaRouteImport.update({
  id: '/auditoria-seguranca',
  path: '/auditoria-seguranca',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAquisicaoRoute = AdminAquisicaoRouteImport.update({
  id: '/aquisicao',
  path: '/aquisicao',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSobreAIaRoute = AuthenticatedSobreAIaRouteImport.update({
  id: '/sobre-a-ia',
  path: '/sobre-a-ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotinasRoute = AuthenticatedRotinasRouteImport.update({
  id: '/rotinas',
  path: '/rotinas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaisRoute = AuthenticatedMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLigarCanalRoute = AuthenticatedLigarCanalRouteImport.update({
  id: '/ligar-canal',
  path: '/ligar-canal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInteracoesRoute = AuthenticatedInteracoesRouteImport.update({
  id: '/interacoes',
  path: '/interacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriveRoute = AuthenticatedDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiversosRoute = AuthenticatedDiversosRouteImport.update({
  id: '/diversos',
  path: '/diversos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDefinicoesRoute = AuthenticatedDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessorRoute = AuthenticatedAssessorRouteImport.update({
  id: '/assessor',
  path: '/assessor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSeguimentosIndexRoute =
  AuthenticatedSeguimentosIndexRouteImport.update({
    id: '/seguimentos/',
    path: '/seguimentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPessoasIndexRoute =
  AuthenticatedPessoasIndexRouteImport.update({
    id: '/pessoas/',
    path: '/pessoas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOportunidadesIndexRoute =
  AuthenticatedOportunidadesIndexRouteImport.update({
    id: '/oportunidades/',
    path: '/oportunidades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegociosIndexRoute =
  AuthenticatedNegociosIndexRouteImport.update({
    id: '/negocios/',
    path: '/negocios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioIndexRoute =
  AuthenticatedNegocioIndexRouteImport.update({
    id: '/negocio/',
    path: '/negocio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImoveisIndexRoute =
  AuthenticatedImoveisIndexRouteImport.update({
    id: '/imoveis/',
    path: '/imoveis/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const OauthOutlookReturnRoute = OauthOutlookReturnRouteImport.update({
  id: '/oauth/outlook/return',
  path: '/oauth/outlook/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBeaconRoute = ApiPublicBeaconRouteImport.update({
  id: '/api/public/beacon',
  path: '/api/public/beacon',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsultorIdRoute = AdminConsultorIdRouteImport.update({
  id: '/consultor/$id',
  path: '/consultor/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSeguimentosIdRoute =
  AuthenticatedSeguimentosIdRouteImport.update({
    id: '/seguimentos/$id',
    path: '/seguimentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotinasIdRoute = AuthenticatedRotinasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRotinasRoute,
} as any)
const AuthenticatedPessoasIdRoute = AuthenticatedPessoasIdRouteImport.update({
  id: '/pessoas/$id',
  path: '/pessoas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOportunidadesIdRoute =
  AuthenticatedOportunidadesIdRouteImport.update({
    id: '/oportunidades/$id',
    path: '/oportunidades/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioFaturacaoRoute =
  AuthenticatedNegocioFaturacaoRouteImport.update({
    id: '/negocio/faturacao',
    path: '/negocio/faturacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioDespesasRoute =
  AuthenticatedNegocioDespesasRouteImport.update({
    id: '/negocio/despesas',
    path: '/negocio/despesas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioComissoesRoute =
  AuthenticatedNegocioComissoesRouteImport.update({
    id: '/negocio/comissoes',
    path: '/negocio/comissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInteracoesIdRoute =
  AuthenticatedInteracoesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedInteracoesRoute,
  } as any)
const AuthenticatedImoveisIdRoute = AuthenticatedImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGruposIdRoute = AuthenticatedGruposIdRouteImport.update({
  id: '/grupos/$id',
  path: '/grupos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriveIdRoute = AuthenticatedDriveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDriveRoute,
} as any)
const AuthenticatedDiversosIdRoute = AuthenticatedDiversosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDiversosRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOportunidadesProspecaoIndexRoute =
  AuthenticatedOportunidadesProspecaoIndexRouteImport.update({
    id: '/oportunidades/prospecao/',
    path: '/oportunidades/prospecao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappTemplateStatusRoute =
  ApiPublicHooksWhatsappTemplateStatusRouteImport.update({
    id: '/api/public/hooks/whatsapp-template-status',
    path: '/api/public/hooks/whatsapp-template-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrialLifecycleRoute =
  ApiPublicHooksTrialLifecycleRouteImport.update({
    id: '/api/public/hooks/trial-lifecycle',
    path: '/api/public/hooks/trial-lifecycle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramRetentionRoute =
  ApiPublicHooksTelegramRetentionRouteImport.update({
    id: '/api/public/hooks/telegram-retention',
    path: '/api/public/hooks/telegram-retention',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSubmitCheckinTemplateRoute =
  ApiPublicHooksSubmitCheckinTemplateRouteImport.update({
    id: '/api/public/hooks/submit-checkin-template',
    path: '/api/public/hooks/submit-checkin-template',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProactiveTickRoute =
  ApiPublicHooksProactiveTickRouteImport.update({
    id: '/api/public/hooks/proactive-tick',
    path: '/api/public/hooks/proactive-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProactivePushRoute =
  ApiPublicHooksProactivePushRouteImport.update({
    id: '/api/public/hooks/proactive-push',
    path: '/api/public/hooks/proactive-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCalendarPollRoute =
  ApiPublicHooksCalendarPollRouteImport.update({
    id: '/api/public/hooks/calendar-poll',
    path: '/api/public/hooks/calendar-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBetaExpiryRoute =
  ApiPublicHooksBetaExpiryRouteImport.update({
    id: '/api/public/hooks/beta-expiry',
    path: '/api/public/hooks/beta-expiry',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOportunidadesProspecaoIdRoute =
  AuthenticatedOportunidadesProspecaoIdRouteImport.update({
    id: '/oportunidades/prospecao/$id',
    path: '/oportunidades/prospecao/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioDespesasIdRoute =
  AuthenticatedNegocioDespesasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedNegocioDespesasRoute,
  } as any)
const AuthenticatedNegocioComissoesIdRoute =
  AuthenticatedNegocioComissoesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedNegocioComissoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/entrar': typeof EntrarRoute
  '/mcp': typeof McpRoute
  '/planos': typeof PlanosRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assessor': typeof AuthenticatedAssessorRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/definicoes': typeof AuthenticatedDefinicoesRoute
  '/diversos': typeof AuthenticatedDiversosRouteWithChildren
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/drive': typeof AuthenticatedDriveRouteWithChildren
  '/hoje': typeof AuthenticatedHojeRoute
  '/interacoes': typeof AuthenticatedInteracoesRouteWithChildren
  '/ligar-canal': typeof AuthenticatedLigarCanalRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/rotinas': typeof AuthenticatedRotinasRouteWithChildren
  '/sobre-a-ia': typeof AuthenticatedSobreAIaRoute
  '/admin/aquisicao': typeof AdminAquisicaoRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/auditoria-seguranca': typeof AdminAuditoriaSegurancaRoute
  '/admin/autonomas': typeof AdminAutonomasRoute
  '/admin/beta': typeof AdminBetaRoute
  '/admin/comunicacao': typeof AdminComunicacaoRoute
  '/admin/convites': typeof AdminConvitesRoute
  '/admin/custos': typeof AdminCustosRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/faturacao': typeof AdminFaturacaoRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/funcionalidades': typeof AdminFuncionalidadesRoute
  '/admin/goldens': typeof AdminGoldensRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/integracoes-flags': typeof AdminIntegracoesFlagsRoute
  '/admin/negocio': typeof AdminNegocioRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/qualidade': typeof AdminQualidadeRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/subscricoes': typeof AdminSubscricoesRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/utilizacao': typeof AdminUtilizacaoRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/diversos/$id': typeof AuthenticatedDiversosIdRoute
  '/drive/$id': typeof AuthenticatedDriveIdRoute
  '/grupos/$id': typeof AuthenticatedGruposIdRoute
  '/imoveis/$id': typeof AuthenticatedImoveisIdRoute
  '/interacoes/$id': typeof AuthenticatedInteracoesIdRoute
  '/negocio/comissoes': typeof AuthenticatedNegocioComissoesRouteWithChildren
  '/negocio/despesas': typeof AuthenticatedNegocioDespesasRouteWithChildren
  '/negocio/faturacao': typeof AuthenticatedNegocioFaturacaoRoute
  '/oportunidades/$id': typeof AuthenticatedOportunidadesIdRoute
  '/pessoas/$id': typeof AuthenticatedPessoasIdRoute
  '/rotinas/$id': typeof AuthenticatedRotinasIdRoute
  '/seguimentos/$id': typeof AuthenticatedSeguimentosIdRoute
  '/admin/consultor/$id': typeof AdminConsultorIdRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/oauth/outlook/return': typeof OauthOutlookReturnRoute
  '/imoveis/': typeof AuthenticatedImoveisIndexRoute
  '/negocio/': typeof AuthenticatedNegocioIndexRoute
  '/negocios/': typeof AuthenticatedNegociosIndexRoute
  '/oportunidades/': typeof AuthenticatedOportunidadesIndexRoute
  '/pessoas/': typeof AuthenticatedPessoasIndexRoute
  '/seguimentos/': typeof AuthenticatedSeguimentosIndexRoute
  '/negocio/comissoes/$id': typeof AuthenticatedNegocioComissoesIdRoute
  '/negocio/despesas/$id': typeof AuthenticatedNegocioDespesasIdRoute
  '/oportunidades/prospecao/$id': typeof AuthenticatedOportunidadesProspecaoIdRoute
  '/api/public/hooks/beta-expiry': typeof ApiPublicHooksBetaExpiryRoute
  '/api/public/hooks/calendar-poll': typeof ApiPublicHooksCalendarPollRoute
  '/api/public/hooks/proactive-push': typeof ApiPublicHooksProactivePushRoute
  '/api/public/hooks/proactive-tick': typeof ApiPublicHooksProactiveTickRoute
  '/api/public/hooks/submit-checkin-template': typeof ApiPublicHooksSubmitCheckinTemplateRoute
  '/api/public/hooks/telegram-retention': typeof ApiPublicHooksTelegramRetentionRoute
  '/api/public/hooks/trial-lifecycle': typeof ApiPublicHooksTrialLifecycleRoute
  '/api/public/hooks/whatsapp-template-status': typeof ApiPublicHooksWhatsappTemplateStatusRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/oportunidades/prospecao/': typeof AuthenticatedOportunidadesProspecaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entrar': typeof EntrarRoute
  '/mcp': typeof McpRoute
  '/planos': typeof PlanosRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assessor': typeof AuthenticatedAssessorRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/definicoes': typeof AuthenticatedDefinicoesRoute
  '/diversos': typeof AuthenticatedDiversosRouteWithChildren
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/drive': typeof AuthenticatedDriveRouteWithChildren
  '/hoje': typeof AuthenticatedHojeRoute
  '/interacoes': typeof AuthenticatedInteracoesRouteWithChildren
  '/ligar-canal': typeof AuthenticatedLigarCanalRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/rotinas': typeof AuthenticatedRotinasRouteWithChildren
  '/sobre-a-ia': typeof AuthenticatedSobreAIaRoute
  '/admin/aquisicao': typeof AdminAquisicaoRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/auditoria-seguranca': typeof AdminAuditoriaSegurancaRoute
  '/admin/autonomas': typeof AdminAutonomasRoute
  '/admin/beta': typeof AdminBetaRoute
  '/admin/comunicacao': typeof AdminComunicacaoRoute
  '/admin/convites': typeof AdminConvitesRoute
  '/admin/custos': typeof AdminCustosRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/faturacao': typeof AdminFaturacaoRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/funcionalidades': typeof AdminFuncionalidadesRoute
  '/admin/goldens': typeof AdminGoldensRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/integracoes-flags': typeof AdminIntegracoesFlagsRoute
  '/admin/negocio': typeof AdminNegocioRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/qualidade': typeof AdminQualidadeRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/subscricoes': typeof AdminSubscricoesRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/utilizacao': typeof AdminUtilizacaoRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/admin': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/diversos/$id': typeof AuthenticatedDiversosIdRoute
  '/drive/$id': typeof AuthenticatedDriveIdRoute
  '/grupos/$id': typeof AuthenticatedGruposIdRoute
  '/imoveis/$id': typeof AuthenticatedImoveisIdRoute
  '/interacoes/$id': typeof AuthenticatedInteracoesIdRoute
  '/negocio/comissoes': typeof AuthenticatedNegocioComissoesRouteWithChildren
  '/negocio/despesas': typeof AuthenticatedNegocioDespesasRouteWithChildren
  '/negocio/faturacao': typeof AuthenticatedNegocioFaturacaoRoute
  '/oportunidades/$id': typeof AuthenticatedOportunidadesIdRoute
  '/pessoas/$id': typeof AuthenticatedPessoasIdRoute
  '/rotinas/$id': typeof AuthenticatedRotinasIdRoute
  '/seguimentos/$id': typeof AuthenticatedSeguimentosIdRoute
  '/admin/consultor/$id': typeof AdminConsultorIdRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/oauth/outlook/return': typeof OauthOutlookReturnRoute
  '/imoveis': typeof AuthenticatedImoveisIndexRoute
  '/negocio': typeof AuthenticatedNegocioIndexRoute
  '/negocios': typeof AuthenticatedNegociosIndexRoute
  '/oportunidades': typeof AuthenticatedOportunidadesIndexRoute
  '/pessoas': typeof AuthenticatedPessoasIndexRoute
  '/seguimentos': typeof AuthenticatedSeguimentosIndexRoute
  '/negocio/comissoes/$id': typeof AuthenticatedNegocioComissoesIdRoute
  '/negocio/despesas/$id': typeof AuthenticatedNegocioDespesasIdRoute
  '/oportunidades/prospecao/$id': typeof AuthenticatedOportunidadesProspecaoIdRoute
  '/api/public/hooks/beta-expiry': typeof ApiPublicHooksBetaExpiryRoute
  '/api/public/hooks/calendar-poll': typeof ApiPublicHooksCalendarPollRoute
  '/api/public/hooks/proactive-push': typeof ApiPublicHooksProactivePushRoute
  '/api/public/hooks/proactive-tick': typeof ApiPublicHooksProactiveTickRoute
  '/api/public/hooks/submit-checkin-template': typeof ApiPublicHooksSubmitCheckinTemplateRoute
  '/api/public/hooks/telegram-retention': typeof ApiPublicHooksTelegramRetentionRoute
  '/api/public/hooks/trial-lifecycle': typeof ApiPublicHooksTrialLifecycleRoute
  '/api/public/hooks/whatsapp-template-status': typeof ApiPublicHooksWhatsappTemplateStatusRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/oportunidades/prospecao': typeof AuthenticatedOportunidadesProspecaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/entrar': typeof EntrarRoute
  '/mcp': typeof McpRoute
  '/planos': typeof PlanosRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/assessor': typeof AuthenticatedAssessorRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/definicoes': typeof AuthenticatedDefinicoesRoute
  '/_authenticated/diversos': typeof AuthenticatedDiversosRouteWithChildren
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/drive': typeof AuthenticatedDriveRouteWithChildren
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/interacoes': typeof AuthenticatedInteracoesRouteWithChildren
  '/_authenticated/ligar-canal': typeof AuthenticatedLigarCanalRoute
  '/_authenticated/mais': typeof AuthenticatedMaisRoute
  '/_authenticated/rotinas': typeof AuthenticatedRotinasRouteWithChildren
  '/_authenticated/sobre-a-ia': typeof AuthenticatedSobreAIaRoute
  '/admin/aquisicao': typeof AdminAquisicaoRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/auditoria-seguranca': typeof AdminAuditoriaSegurancaRoute
  '/admin/autonomas': typeof AdminAutonomasRoute
  '/admin/beta': typeof AdminBetaRoute
  '/admin/comunicacao': typeof AdminComunicacaoRoute
  '/admin/convites': typeof AdminConvitesRoute
  '/admin/custos': typeof AdminCustosRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/faturacao': typeof AdminFaturacaoRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/funcionalidades': typeof AdminFuncionalidadesRoute
  '/admin/goldens': typeof AdminGoldensRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/integracoes-flags': typeof AdminIntegracoesFlagsRoute
  '/admin/negocio': typeof AdminNegocioRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/qualidade': typeof AdminQualidadeRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/subscricoes': typeof AdminSubscricoesRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/utilizacao': typeof AdminUtilizacaoRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/diversos/$id': typeof AuthenticatedDiversosIdRoute
  '/_authenticated/drive/$id': typeof AuthenticatedDriveIdRoute
  '/_authenticated/grupos/$id': typeof AuthenticatedGruposIdRoute
  '/_authenticated/imoveis/$id': typeof AuthenticatedImoveisIdRoute
  '/_authenticated/interacoes/$id': typeof AuthenticatedInteracoesIdRoute
  '/_authenticated/negocio/comissoes': typeof AuthenticatedNegocioComissoesRouteWithChildren
  '/_authenticated/negocio/despesas': typeof AuthenticatedNegocioDespesasRouteWithChildren
  '/_authenticated/negocio/faturacao': typeof AuthenticatedNegocioFaturacaoRoute
  '/_authenticated/oportunidades/$id': typeof AuthenticatedOportunidadesIdRoute
  '/_authenticated/pessoas/$id': typeof AuthenticatedPessoasIdRoute
  '/_authenticated/rotinas/$id': typeof AuthenticatedRotinasIdRoute
  '/_authenticated/seguimentos/$id': typeof AuthenticatedSeguimentosIdRoute
  '/admin/consultor/$id': typeof AdminConsultorIdRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/oauth/outlook/return': typeof OauthOutlookReturnRoute
  '/_authenticated/imoveis/': typeof AuthenticatedImoveisIndexRoute
  '/_authenticated/negocio/': typeof AuthenticatedNegocioIndexRoute
  '/_authenticated/negocios/': typeof AuthenticatedNegociosIndexRoute
  '/_authenticated/oportunidades/': typeof AuthenticatedOportunidadesIndexRoute
  '/_authenticated/pessoas/': typeof AuthenticatedPessoasIndexRoute
  '/_authenticated/seguimentos/': typeof AuthenticatedSeguimentosIndexRoute
  '/_authenticated/negocio/comissoes/$id': typeof AuthenticatedNegocioComissoesIdRoute
  '/_authenticated/negocio/despesas/$id': typeof AuthenticatedNegocioDespesasIdRoute
  '/_authenticated/oportunidades/prospecao/$id': typeof AuthenticatedOportunidadesProspecaoIdRoute
  '/api/public/hooks/beta-expiry': typeof ApiPublicHooksBetaExpiryRoute
  '/api/public/hooks/calendar-poll': typeof ApiPublicHooksCalendarPollRoute
  '/api/public/hooks/proactive-push': typeof ApiPublicHooksProactivePushRoute
  '/api/public/hooks/proactive-tick': typeof ApiPublicHooksProactiveTickRoute
  '/api/public/hooks/submit-checkin-template': typeof ApiPublicHooksSubmitCheckinTemplateRoute
  '/api/public/hooks/telegram-retention': typeof ApiPublicHooksTelegramRetentionRoute
  '/api/public/hooks/trial-lifecycle': typeof ApiPublicHooksTrialLifecycleRoute
  '/api/public/hooks/whatsapp-template-status': typeof ApiPublicHooksWhatsappTemplateStatusRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/_authenticated/oportunidades/prospecao/': typeof AuthenticatedOportunidadesProspecaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/entrar'
    | '/mcp'
    | '/planos'
    | '/registo'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assessor'
    | '/calendario'
    | '/definicoes'
    | '/diversos'
    | '/documentos'
    | '/drive'
    | '/hoje'
    | '/interacoes'
    | '/ligar-canal'
    | '/mais'
    | '/rotinas'
    | '/sobre-a-ia'
    | '/admin/aquisicao'
    | '/admin/auditoria'
    | '/admin/auditoria-seguranca'
    | '/admin/autonomas'
    | '/admin/beta'
    | '/admin/comunicacao'
    | '/admin/convites'
    | '/admin/custos'
    | '/admin/definicoes'
    | '/admin/faturacao'
    | '/admin/feedback'
    | '/admin/funcionalidades'
    | '/admin/goldens'
    | '/admin/integracoes'
    | '/admin/integracoes-flags'
    | '/admin/negocio'
    | '/admin/planos'
    | '/admin/qualidade'
    | '/admin/seguranca'
    | '/admin/subscricoes'
    | '/admin/suporte'
    | '/admin/utilizacao'
    | '/admin/utilizadores'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
    | '/diversos/$id'
    | '/drive/$id'
    | '/grupos/$id'
    | '/imoveis/$id'
    | '/interacoes/$id'
    | '/negocio/comissoes'
    | '/negocio/despesas'
    | '/negocio/faturacao'
    | '/oportunidades/$id'
    | '/pessoas/$id'
    | '/rotinas/$id'
    | '/seguimentos/$id'
    | '/admin/consultor/$id'
    | '/api/public/beacon'
    | '/api/public/whatsapp-webhook'
    | '/oauth/google-calendar/return'
    | '/oauth/outlook/return'
    | '/imoveis/'
    | '/negocio/'
    | '/negocios/'
    | '/oportunidades/'
    | '/pessoas/'
    | '/seguimentos/'
    | '/negocio/comissoes/$id'
    | '/negocio/despesas/$id'
    | '/oportunidades/prospecao/$id'
    | '/api/public/hooks/beta-expiry'
    | '/api/public/hooks/calendar-poll'
    | '/api/public/hooks/proactive-push'
    | '/api/public/hooks/proactive-tick'
    | '/api/public/hooks/submit-checkin-template'
    | '/api/public/hooks/telegram-retention'
    | '/api/public/hooks/trial-lifecycle'
    | '/api/public/hooks/whatsapp-template-status'
    | '/api/public/telegram/webhook'
    | '/oportunidades/prospecao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/entrar'
    | '/mcp'
    | '/planos'
    | '/registo'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assessor'
    | '/calendario'
    | '/definicoes'
    | '/diversos'
    | '/documentos'
    | '/drive'
    | '/hoje'
    | '/interacoes'
    | '/ligar-canal'
    | '/mais'
    | '/rotinas'
    | '/sobre-a-ia'
    | '/admin/aquisicao'
    | '/admin/auditoria'
    | '/admin/auditoria-seguranca'
    | '/admin/autonomas'
    | '/admin/beta'
    | '/admin/comunicacao'
    | '/admin/convites'
    | '/admin/custos'
    | '/admin/definicoes'
    | '/admin/faturacao'
    | '/admin/feedback'
    | '/admin/funcionalidades'
    | '/admin/goldens'
    | '/admin/integracoes'
    | '/admin/integracoes-flags'
    | '/admin/negocio'
    | '/admin/planos'
    | '/admin/qualidade'
    | '/admin/seguranca'
    | '/admin/subscricoes'
    | '/admin/suporte'
    | '/admin/utilizacao'
    | '/admin/utilizadores'
    | '/admin'
    | '/.mcp/invoke-tool/$tool'
    | '/diversos/$id'
    | '/drive/$id'
    | '/grupos/$id'
    | '/imoveis/$id'
    | '/interacoes/$id'
    | '/negocio/comissoes'
    | '/negocio/despesas'
    | '/negocio/faturacao'
    | '/oportunidades/$id'
    | '/pessoas/$id'
    | '/rotinas/$id'
    | '/seguimentos/$id'
    | '/admin/consultor/$id'
    | '/api/public/beacon'
    | '/api/public/whatsapp-webhook'
    | '/oauth/google-calendar/return'
    | '/oauth/outlook/return'
    | '/imoveis'
    | '/negocio'
    | '/negocios'
    | '/oportunidades'
    | '/pessoas'
    | '/seguimentos'
    | '/negocio/comissoes/$id'
    | '/negocio/despesas/$id'
    | '/oportunidades/prospecao/$id'
    | '/api/public/hooks/beta-expiry'
    | '/api/public/hooks/calendar-poll'
    | '/api/public/hooks/proactive-push'
    | '/api/public/hooks/proactive-tick'
    | '/api/public/hooks/submit-checkin-template'
    | '/api/public/hooks/telegram-retention'
    | '/api/public/hooks/trial-lifecycle'
    | '/api/public/hooks/whatsapp-template-status'
    | '/api/public/telegram/webhook'
    | '/oportunidades/prospecao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/entrar'
    | '/mcp'
    | '/planos'
    | '/registo'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/assessor'
    | '/_authenticated/calendario'
    | '/_authenticated/definicoes'
    | '/_authenticated/diversos'
    | '/_authenticated/documentos'
    | '/_authenticated/drive'
    | '/_authenticated/hoje'
    | '/_authenticated/interacoes'
    | '/_authenticated/ligar-canal'
    | '/_authenticated/mais'
    | '/_authenticated/rotinas'
    | '/_authenticated/sobre-a-ia'
    | '/admin/aquisicao'
    | '/admin/auditoria'
    | '/admin/auditoria-seguranca'
    | '/admin/autonomas'
    | '/admin/beta'
    | '/admin/comunicacao'
    | '/admin/convites'
    | '/admin/custos'
    | '/admin/definicoes'
    | '/admin/faturacao'
    | '/admin/feedback'
    | '/admin/funcionalidades'
    | '/admin/goldens'
    | '/admin/integracoes'
    | '/admin/integracoes-flags'
    | '/admin/negocio'
    | '/admin/planos'
    | '/admin/qualidade'
    | '/admin/seguranca'
    | '/admin/subscricoes'
    | '/admin/suporte'
    | '/admin/utilizacao'
    | '/admin/utilizadores'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/diversos/$id'
    | '/_authenticated/drive/$id'
    | '/_authenticated/grupos/$id'
    | '/_authenticated/imoveis/$id'
    | '/_authenticated/interacoes/$id'
    | '/_authenticated/negocio/comissoes'
    | '/_authenticated/negocio/despesas'
    | '/_authenticated/negocio/faturacao'
    | '/_authenticated/oportunidades/$id'
    | '/_authenticated/pessoas/$id'
    | '/_authenticated/rotinas/$id'
    | '/_authenticated/seguimentos/$id'
    | '/admin/consultor/$id'
    | '/api/public/beacon'
    | '/api/public/whatsapp-webhook'
    | '/oauth/google-calendar/return'
    | '/oauth/outlook/return'
    | '/_authenticated/imoveis/'
    | '/_authenticated/negocio/'
    | '/_authenticated/negocios/'
    | '/_authenticated/oportunidades/'
    | '/_authenticated/pessoas/'
    | '/_authenticated/seguimentos/'
    | '/_authenticated/negocio/comissoes/$id'
    | '/_authenticated/negocio/despesas/$id'
    | '/_authenticated/oportunidades/prospecao/$id'
    | '/api/public/hooks/beta-expiry'
    | '/api/public/hooks/calendar-poll'
    | '/api/public/hooks/proactive-push'
    | '/api/public/hooks/proactive-tick'
    | '/api/public/hooks/submit-checkin-template'
    | '/api/public/hooks/telegram-retention'
    | '/api/public/hooks/trial-lifecycle'
    | '/api/public/hooks/whatsapp-template-status'
    | '/api/public/telegram/webhook'
    | '/_authenticated/oportunidades/prospecao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EntrarRoute: typeof EntrarRoute
  McpRoute: typeof McpRoute
  PlanosRoute: typeof PlanosRoute
  RegistoRoute: typeof RegistoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBeaconRoute: typeof ApiPublicBeaconRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
  OauthOutlookReturnRoute: typeof OauthOutlookReturnRoute
  ApiPublicHooksBetaExpiryRoute: typeof ApiPublicHooksBetaExpiryRoute
  ApiPublicHooksCalendarPollRoute: typeof ApiPublicHooksCalendarPollRoute
  ApiPublicHooksProactivePushRoute: typeof ApiPublicHooksProactivePushRoute
  ApiPublicHooksProactiveTickRoute: typeof ApiPublicHooksProactiveTickRoute
  ApiPublicHooksSubmitCheckinTemplateRoute: typeof ApiPublicHooksSubmitCheckinTemplateRoute
  ApiPublicHooksTelegramRetentionRoute: typeof ApiPublicHooksTelegramRetentionRoute
  ApiPublicHooksTrialLifecycleRoute: typeof ApiPublicHooksTrialLifecycleRoute
  ApiPublicHooksWhatsappTemplateStatusRoute: typeof ApiPublicHooksWhatsappTemplateStatusRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/utilizadores': {
      id: '/admin/utilizadores'
      path: '/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AdminUtilizadoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/utilizacao': {
      id: '/admin/utilizacao'
      path: '/utilizacao'
      fullPath: '/admin/utilizacao'
      preLoaderRoute: typeof AdminUtilizacaoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subscricoes': {
      id: '/admin/subscricoes'
      path: '/subscricoes'
      fullPath: '/admin/subscricoes'
      preLoaderRoute: typeof AdminSubscricoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seguranca': {
      id: '/admin/seguranca'
      path: '/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/qualidade': {
      id: '/admin/qualidade'
      path: '/qualidade'
      fullPath: '/admin/qualidade'
      preLoaderRoute: typeof AdminQualidadeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/negocio': {
      id: '/admin/negocio'
      path: '/negocio'
      fullPath: '/admin/negocio'
      preLoaderRoute: typeof AdminNegocioRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/integracoes-flags': {
      id: '/admin/integracoes-flags'
      path: '/integracoes-flags'
      fullPath: '/admin/integracoes-flags'
      preLoaderRoute: typeof AdminIntegracoesFlagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/goldens': {
      id: '/admin/goldens'
      path: '/goldens'
      fullPath: '/admin/goldens'
      preLoaderRoute: typeof AdminGoldensRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/funcionalidades': {
      id: '/admin/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/admin/funcionalidades'
      preLoaderRoute: typeof AdminFuncionalidadesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faturacao': {
      id: '/admin/faturacao'
      path: '/faturacao'
      fullPath: '/admin/faturacao'
      preLoaderRoute: typeof AdminFaturacaoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/definicoes': {
      id: '/admin/definicoes'
      path: '/definicoes'
      fullPath: '/admin/definicoes'
      preLoaderRoute: typeof AdminDefinicoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/custos': {
      id: '/admin/custos'
      path: '/custos'
      fullPath: '/admin/custos'
      preLoaderRoute: typeof AdminCustosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/convites': {
      id: '/admin/convites'
      path: '/convites'
      fullPath: '/admin/convites'
      preLoaderRoute: typeof AdminConvitesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comunicacao': {
      id: '/admin/comunicacao'
      path: '/comunicacao'
      fullPath: '/admin/comunicacao'
      preLoaderRoute: typeof AdminComunicacaoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/beta': {
      id: '/admin/beta'
      path: '/beta'
      fullPath: '/admin/beta'
      preLoaderRoute: typeof AdminBetaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/autonomas': {
      id: '/admin/autonomas'
      path: '/autonomas'
      fullPath: '/admin/autonomas'
      preLoaderRoute: typeof AdminAutonomasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/auditoria-seguranca': {
      id: '/admin/auditoria-seguranca'
      path: '/auditoria-seguranca'
      fullPath: '/admin/auditoria-seguranca'
      preLoaderRoute: typeof AdminAuditoriaSegurancaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/aquisicao': {
      id: '/admin/aquisicao'
      path: '/aquisicao'
      fullPath: '/admin/aquisicao'
      preLoaderRoute: typeof AdminAquisicaoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/sobre-a-ia': {
      id: '/_authenticated/sobre-a-ia'
      path: '/sobre-a-ia'
      fullPath: '/sobre-a-ia'
      preLoaderRoute: typeof AuthenticatedSobreAIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotinas': {
      id: '/_authenticated/rotinas'
      path: '/rotinas'
      fullPath: '/rotinas'
      preLoaderRoute: typeof AuthenticatedRotinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mais': {
      id: '/_authenticated/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AuthenticatedMaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ligar-canal': {
      id: '/_authenticated/ligar-canal'
      path: '/ligar-canal'
      fullPath: '/ligar-canal'
      preLoaderRoute: typeof AuthenticatedLigarCanalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interacoes': {
      id: '/_authenticated/interacoes'
      path: '/interacoes'
      fullPath: '/interacoes'
      preLoaderRoute: typeof AuthenticatedInteracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive': {
      id: '/_authenticated/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof AuthenticatedDriveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diversos': {
      id: '/_authenticated/diversos'
      path: '/diversos'
      fullPath: '/diversos'
      preLoaderRoute: typeof AuthenticatedDiversosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/definicoes': {
      id: '/_authenticated/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof AuthenticatedDefinicoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessor': {
      id: '/_authenticated/assessor'
      path: '/assessor'
      fullPath: '/assessor'
      preLoaderRoute: typeof AuthenticatedAssessorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seguimentos/': {
      id: '/_authenticated/seguimentos/'
      path: '/seguimentos'
      fullPath: '/seguimentos/'
      preLoaderRoute: typeof AuthenticatedSeguimentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pessoas/': {
      id: '/_authenticated/pessoas/'
      path: '/pessoas'
      fullPath: '/pessoas/'
      preLoaderRoute: typeof AuthenticatedPessoasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oportunidades/': {
      id: '/_authenticated/oportunidades/'
      path: '/oportunidades'
      fullPath: '/oportunidades/'
      preLoaderRoute: typeof AuthenticatedOportunidadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios/': {
      id: '/_authenticated/negocios/'
      path: '/negocios'
      fullPath: '/negocios/'
      preLoaderRoute: typeof AuthenticatedNegociosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/': {
      id: '/_authenticated/negocio/'
      path: '/negocio'
      fullPath: '/negocio/'
      preLoaderRoute: typeof AuthenticatedNegocioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imoveis/': {
      id: '/_authenticated/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof AuthenticatedImoveisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/outlook/return': {
      id: '/oauth/outlook/return'
      path: '/oauth/outlook/return'
      fullPath: '/oauth/outlook/return'
      preLoaderRoute: typeof OauthOutlookReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/beacon': {
      id: '/api/public/beacon'
      path: '/api/public/beacon'
      fullPath: '/api/public/beacon'
      preLoaderRoute: typeof ApiPublicBeaconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/consultor/$id': {
      id: '/admin/consultor/$id'
      path: '/consultor/$id'
      fullPath: '/admin/consultor/$id'
      preLoaderRoute: typeof AdminConsultorIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/seguimentos/$id': {
      id: '/_authenticated/seguimentos/$id'
      path: '/seguimentos/$id'
      fullPath: '/seguimentos/$id'
      preLoaderRoute: typeof AuthenticatedSeguimentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotinas/$id': {
      id: '/_authenticated/rotinas/$id'
      path: '/$id'
      fullPath: '/rotinas/$id'
      preLoaderRoute: typeof AuthenticatedRotinasIdRouteImport
      parentRoute: typeof AuthenticatedRotinasRoute
    }
    '/_authenticated/pessoas/$id': {
      id: '/_authenticated/pessoas/$id'
      path: '/pessoas/$id'
      fullPath: '/pessoas/$id'
      preLoaderRoute: typeof AuthenticatedPessoasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oportunidades/$id': {
      id: '/_authenticated/oportunidades/$id'
      path: '/oportunidades/$id'
      fullPath: '/oportunidades/$id'
      preLoaderRoute: typeof AuthenticatedOportunidadesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/faturacao': {
      id: '/_authenticated/negocio/faturacao'
      path: '/negocio/faturacao'
      fullPath: '/negocio/faturacao'
      preLoaderRoute: typeof AuthenticatedNegocioFaturacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/despesas': {
      id: '/_authenticated/negocio/despesas'
      path: '/negocio/despesas'
      fullPath: '/negocio/despesas'
      preLoaderRoute: typeof AuthenticatedNegocioDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/comissoes': {
      id: '/_authenticated/negocio/comissoes'
      path: '/negocio/comissoes'
      fullPath: '/negocio/comissoes'
      preLoaderRoute: typeof AuthenticatedNegocioComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interacoes/$id': {
      id: '/_authenticated/interacoes/$id'
      path: '/$id'
      fullPath: '/interacoes/$id'
      preLoaderRoute: typeof AuthenticatedInteracoesIdRouteImport
      parentRoute: typeof AuthenticatedInteracoesRoute
    }
    '/_authenticated/imoveis/$id': {
      id: '/_authenticated/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof AuthenticatedImoveisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupos/$id': {
      id: '/_authenticated/grupos/$id'
      path: '/grupos/$id'
      fullPath: '/grupos/$id'
      preLoaderRoute: typeof AuthenticatedGruposIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/$id': {
      id: '/_authenticated/drive/$id'
      path: '/$id'
      fullPath: '/drive/$id'
      preLoaderRoute: typeof AuthenticatedDriveIdRouteImport
      parentRoute: typeof AuthenticatedDriveRoute
    }
    '/_authenticated/diversos/$id': {
      id: '/_authenticated/diversos/$id'
      path: '/$id'
      fullPath: '/diversos/$id'
      preLoaderRoute: typeof AuthenticatedDiversosIdRouteImport
      parentRoute: typeof AuthenticatedDiversosRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/oportunidades/prospecao/': {
      id: '/_authenticated/oportunidades/prospecao/'
      path: '/oportunidades/prospecao'
      fullPath: '/oportunidades/prospecao/'
      preLoaderRoute: typeof AuthenticatedOportunidadesProspecaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-template-status': {
      id: '/api/public/hooks/whatsapp-template-status'
      path: '/api/public/hooks/whatsapp-template-status'
      fullPath: '/api/public/hooks/whatsapp-template-status'
      preLoaderRoute: typeof ApiPublicHooksWhatsappTemplateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trial-lifecycle': {
      id: '/api/public/hooks/trial-lifecycle'
      path: '/api/public/hooks/trial-lifecycle'
      fullPath: '/api/public/hooks/trial-lifecycle'
      preLoaderRoute: typeof ApiPublicHooksTrialLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-retention': {
      id: '/api/public/hooks/telegram-retention'
      path: '/api/public/hooks/telegram-retention'
      fullPath: '/api/public/hooks/telegram-retention'
      preLoaderRoute: typeof ApiPublicHooksTelegramRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/submit-checkin-template': {
      id: '/api/public/hooks/submit-checkin-template'
      path: '/api/public/hooks/submit-checkin-template'
      fullPath: '/api/public/hooks/submit-checkin-template'
      preLoaderRoute: typeof ApiPublicHooksSubmitCheckinTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/proactive-tick': {
      id: '/api/public/hooks/proactive-tick'
      path: '/api/public/hooks/proactive-tick'
      fullPath: '/api/public/hooks/proactive-tick'
      preLoaderRoute: typeof ApiPublicHooksProactiveTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/proactive-push': {
      id: '/api/public/hooks/proactive-push'
      path: '/api/public/hooks/proactive-push'
      fullPath: '/api/public/hooks/proactive-push'
      preLoaderRoute: typeof ApiPublicHooksProactivePushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/calendar-poll': {
      id: '/api/public/hooks/calendar-poll'
      path: '/api/public/hooks/calendar-poll'
      fullPath: '/api/public/hooks/calendar-poll'
      preLoaderRoute: typeof ApiPublicHooksCalendarPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/beta-expiry': {
      id: '/api/public/hooks/beta-expiry'
      path: '/api/public/hooks/beta-expiry'
      fullPath: '/api/public/hooks/beta-expiry'
      preLoaderRoute: typeof ApiPublicHooksBetaExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/oportunidades/prospecao/$id': {
      id: '/_authenticated/oportunidades/prospecao/$id'
      path: '/oportunidades/prospecao/$id'
      fullPath: '/oportunidades/prospecao/$id'
      preLoaderRoute: typeof AuthenticatedOportunidadesProspecaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/despesas/$id': {
      id: '/_authenticated/negocio/despesas/$id'
      path: '/$id'
      fullPath: '/negocio/despesas/$id'
      preLoaderRoute: typeof AuthenticatedNegocioDespesasIdRouteImport
      parentRoute: typeof AuthenticatedNegocioDespesasRoute
    }
    '/_authenticated/negocio/comissoes/$id': {
      id: '/_authenticated/negocio/comissoes/$id'
      path: '/$id'
      fullPath: '/negocio/comissoes/$id'
      preLoaderRoute: typeof AuthenticatedNegocioComissoesIdRouteImport
      parentRoute: typeof AuthenticatedNegocioComissoesRoute
    }
  }
}

interface AuthenticatedDiversosRouteChildren {
  AuthenticatedDiversosIdRoute: typeof AuthenticatedDiversosIdRoute
}

const AuthenticatedDiversosRouteChildren: AuthenticatedDiversosRouteChildren = {
  AuthenticatedDiversosIdRoute: AuthenticatedDiversosIdRoute,
}

const AuthenticatedDiversosRouteWithChildren =
  AuthenticatedDiversosRoute._addFileChildren(
    AuthenticatedDiversosRouteChildren,
  )

interface AuthenticatedDriveRouteChildren {
  AuthenticatedDriveIdRoute: typeof AuthenticatedDriveIdRoute
}

const AuthenticatedDriveRouteChildren: AuthenticatedDriveRouteChildren = {
  AuthenticatedDriveIdRoute: AuthenticatedDriveIdRoute,
}

const AuthenticatedDriveRouteWithChildren =
  AuthenticatedDriveRoute._addFileChildren(AuthenticatedDriveRouteChildren)

interface AuthenticatedInteracoesRouteChildren {
  AuthenticatedInteracoesIdRoute: typeof AuthenticatedInteracoesIdRoute
}

const AuthenticatedInteracoesRouteChildren: AuthenticatedInteracoesRouteChildren =
  {
    AuthenticatedInteracoesIdRoute: AuthenticatedInteracoesIdRoute,
  }

const AuthenticatedInteracoesRouteWithChildren =
  AuthenticatedInteracoesRoute._addFileChildren(
    AuthenticatedInteracoesRouteChildren,
  )

interface AuthenticatedRotinasRouteChildren {
  AuthenticatedRotinasIdRoute: typeof AuthenticatedRotinasIdRoute
}

const AuthenticatedRotinasRouteChildren: AuthenticatedRotinasRouteChildren = {
  AuthenticatedRotinasIdRoute: AuthenticatedRotinasIdRoute,
}

const AuthenticatedRotinasRouteWithChildren =
  AuthenticatedRotinasRoute._addFileChildren(AuthenticatedRotinasRouteChildren)

interface AuthenticatedNegocioComissoesRouteChildren {
  AuthenticatedNegocioComissoesIdRoute: typeof AuthenticatedNegocioComissoesIdRoute
}

const AuthenticatedNegocioComissoesRouteChildren: AuthenticatedNegocioComissoesRouteChildren =
  {
    AuthenticatedNegocioComissoesIdRoute: AuthenticatedNegocioComissoesIdRoute,
  }

const AuthenticatedNegocioComissoesRouteWithChildren =
  AuthenticatedNegocioComissoesRoute._addFileChildren(
    AuthenticatedNegocioComissoesRouteChildren,
  )

interface AuthenticatedNegocioDespesasRouteChildren {
  AuthenticatedNegocioDespesasIdRoute: typeof AuthenticatedNegocioDespesasIdRoute
}

const AuthenticatedNegocioDespesasRouteChildren: AuthenticatedNegocioDespesasRouteChildren =
  {
    AuthenticatedNegocioDespesasIdRoute: AuthenticatedNegocioDespesasIdRoute,
  }

const AuthenticatedNegocioDespesasRouteWithChildren =
  AuthenticatedNegocioDespesasRoute._addFileChildren(
    AuthenticatedNegocioDespesasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessorRoute: typeof AuthenticatedAssessorRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedDefinicoesRoute: typeof AuthenticatedDefinicoesRoute
  AuthenticatedDiversosRoute: typeof AuthenticatedDiversosRouteWithChildren
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedDriveRoute: typeof AuthenticatedDriveRouteWithChildren
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedInteracoesRoute: typeof AuthenticatedInteracoesRouteWithChildren
  AuthenticatedLigarCanalRoute: typeof AuthenticatedLigarCanalRoute
  AuthenticatedMaisRoute: typeof AuthenticatedMaisRoute
  AuthenticatedRotinasRoute: typeof AuthenticatedRotinasRouteWithChildren
  AuthenticatedSobreAIaRoute: typeof AuthenticatedSobreAIaRoute
  AuthenticatedGruposIdRoute: typeof AuthenticatedGruposIdRoute
  AuthenticatedImoveisIdRoute: typeof AuthenticatedImoveisIdRoute
  AuthenticatedNegocioComissoesRoute: typeof AuthenticatedNegocioComissoesRouteWithChildren
  AuthenticatedNegocioDespesasRoute: typeof AuthenticatedNegocioDespesasRouteWithChildren
  AuthenticatedNegocioFaturacaoRoute: typeof AuthenticatedNegocioFaturacaoRoute
  AuthenticatedOportunidadesIdRoute: typeof AuthenticatedOportunidadesIdRoute
  AuthenticatedPessoasIdRoute: typeof AuthenticatedPessoasIdRoute
  AuthenticatedSeguimentosIdRoute: typeof AuthenticatedSeguimentosIdRoute
  AuthenticatedImoveisIndexRoute: typeof AuthenticatedImoveisIndexRoute
  AuthenticatedNegocioIndexRoute: typeof AuthenticatedNegocioIndexRoute
  AuthenticatedNegociosIndexRoute: typeof AuthenticatedNegociosIndexRoute
  AuthenticatedOportunidadesIndexRoute: typeof AuthenticatedOportunidadesIndexRoute
  AuthenticatedPessoasIndexRoute: typeof AuthenticatedPessoasIndexRoute
  AuthenticatedSeguimentosIndexRoute: typeof AuthenticatedSeguimentosIndexRoute
  AuthenticatedOportunidadesProspecaoIdRoute: typeof AuthenticatedOportunidadesProspecaoIdRoute
  AuthenticatedOportunidadesProspecaoIndexRoute: typeof AuthenticatedOportunidadesProspecaoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessorRoute: AuthenticatedAssessorRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedDefinicoesRoute: AuthenticatedDefinicoesRoute,
  AuthenticatedDiversosRoute: AuthenticatedDiversosRouteWithChildren,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedDriveRoute: AuthenticatedDriveRouteWithChildren,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedInteracoesRoute: AuthenticatedInteracoesRouteWithChildren,
  AuthenticatedLigarCanalRoute: AuthenticatedLigarCanalRoute,
  AuthenticatedMaisRoute: AuthenticatedMaisRoute,
  AuthenticatedRotinasRoute: AuthenticatedRotinasRouteWithChildren,
  AuthenticatedSobreAIaRoute: AuthenticatedSobreAIaRoute,
  AuthenticatedGruposIdRoute: AuthenticatedGruposIdRoute,
  AuthenticatedImoveisIdRoute: AuthenticatedImoveisIdRoute,
  AuthenticatedNegocioComissoesRoute:
    AuthenticatedNegocioComissoesRouteWithChildren,
  AuthenticatedNegocioDespesasRoute:
    AuthenticatedNegocioDespesasRouteWithChildren,
  AuthenticatedNegocioFaturacaoRoute: AuthenticatedNegocioFaturacaoRoute,
  AuthenticatedOportunidadesIdRoute: AuthenticatedOportunidadesIdRoute,
  AuthenticatedPessoasIdRoute: AuthenticatedPessoasIdRoute,
  AuthenticatedSeguimentosIdRoute: AuthenticatedSeguimentosIdRoute,
  AuthenticatedImoveisIndexRoute: AuthenticatedImoveisIndexRoute,
  AuthenticatedNegocioIndexRoute: AuthenticatedNegocioIndexRoute,
  AuthenticatedNegociosIndexRoute: AuthenticatedNegociosIndexRoute,
  AuthenticatedOportunidadesIndexRoute: AuthenticatedOportunidadesIndexRoute,
  AuthenticatedPessoasIndexRoute: AuthenticatedPessoasIndexRoute,
  AuthenticatedSeguimentosIndexRoute: AuthenticatedSeguimentosIndexRoute,
  AuthenticatedOportunidadesProspecaoIdRoute:
    AuthenticatedOportunidadesProspecaoIdRoute,
  AuthenticatedOportunidadesProspecaoIndexRoute:
    AuthenticatedOportunidadesProspecaoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAquisicaoRoute: typeof AdminAquisicaoRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminAuditoriaSegurancaRoute: typeof AdminAuditoriaSegurancaRoute
  AdminAutonomasRoute: typeof AdminAutonomasRoute
  AdminBetaRoute: typeof AdminBetaRoute
  AdminComunicacaoRoute: typeof AdminComunicacaoRoute
  AdminConvitesRoute: typeof AdminConvitesRoute
  AdminCustosRoute: typeof AdminCustosRoute
  AdminDefinicoesRoute: typeof AdminDefinicoesRoute
  AdminFaturacaoRoute: typeof AdminFaturacaoRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminFuncionalidadesRoute: typeof AdminFuncionalidadesRoute
  AdminGoldensRoute: typeof AdminGoldensRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminIntegracoesFlagsRoute: typeof AdminIntegracoesFlagsRoute
  AdminNegocioRoute: typeof AdminNegocioRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminQualidadeRoute: typeof AdminQualidadeRoute
  AdminSegurancaRoute: typeof AdminSegurancaRoute
  AdminSubscricoesRoute: typeof AdminSubscricoesRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminUtilizacaoRoute: typeof AdminUtilizacaoRoute
  AdminUtilizadoresRoute: typeof AdminUtilizadoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConsultorIdRoute: typeof AdminConsultorIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAquisicaoRoute: AdminAquisicaoRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminAuditoriaSegurancaRoute: AdminAuditoriaSegurancaRoute,
  AdminAutonomasRoute: AdminAutonomasRoute,
  AdminBetaRoute: AdminBetaRoute,
  AdminComunicacaoRoute: AdminComunicacaoRoute,
  AdminConvitesRoute: AdminConvitesRoute,
  AdminCustosRoute: AdminCustosRoute,
  AdminDefinicoesRoute: AdminDefinicoesRoute,
  AdminFaturacaoRoute: AdminFaturacaoRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminFuncionalidadesRoute: AdminFuncionalidadesRoute,
  AdminGoldensRoute: AdminGoldensRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminIntegracoesFlagsRoute: AdminIntegracoesFlagsRoute,
  AdminNegocioRoute: AdminNegocioRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminQualidadeRoute: AdminQualidadeRoute,
  AdminSegurancaRoute: AdminSegurancaRoute,
  AdminSubscricoesRoute: AdminSubscricoesRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminUtilizacaoRoute: AdminUtilizacaoRoute,
  AdminUtilizadoresRoute: AdminUtilizadoresRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConsultorIdRoute: AdminConsultorIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EntrarRoute: EntrarRoute,
  McpRoute: McpRoute,
  PlanosRoute: PlanosRoute,
  RegistoRoute: RegistoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBeaconRoute: ApiPublicBeaconRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
  OauthOutlookReturnRoute: OauthOutlookReturnRoute,
  ApiPublicHooksBetaExpiryRoute: ApiPublicHooksBetaExpiryRoute,
  ApiPublicHooksCalendarPollRoute: ApiPublicHooksCalendarPollRoute,
  ApiPublicHooksProactivePushRoute: ApiPublicHooksProactivePushRoute,
  ApiPublicHooksProactiveTickRoute: ApiPublicHooksProactiveTickRoute,
  ApiPublicHooksSubmitCheckinTemplateRoute:
    ApiPublicHooksSubmitCheckinTemplateRoute,
  ApiPublicHooksTelegramRetentionRoute: ApiPublicHooksTelegramRetentionRoute,
  ApiPublicHooksTrialLifecycleRoute: ApiPublicHooksTrialLifecycleRoute,
  ApiPublicHooksWhatsappTemplateStatusRoute:
    ApiPublicHooksWhatsappTemplateStatusRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
